<?php
/**
* Soap client Net2E
*
* Autogenerated with the Yii extension wsdl2php.
*/



class TopupPpCardForPartners
{
public $partnerCode; //string; ma doi tac
public $cardName; //string; ten the 1. ONCASH, 2. VINACARD, 3. MOBICARD, 4. VIETTELCARD
public $transID; //string; ma giao dich gui den net2e
public $userName; //string; ten/ ma tai khoan  yeu cau nap the
public $topupAmount; //string; so tien nap the, default 0
public $cardSerial; //string; so seri the
public $PinCodeBase64; //string; ma so yeu cau duoi lop trang bac
public $customerIP; //string; ip may chu
public $description; //string; mo ta giao dich, null
public $signature; //string;
public $language; //string; ngon ngu nhan loi vi-VN 
public $cardPrice; //string;
public $cardOnCash; //string;
public $lreturnCode; //string;
}

class TopupPpCardForPartnersResponse
{
//public $return; //string;
//public $Response; //Bool;
public $TopupPpCardForPartnersResult; //boolean;
public $returnSerial; //string;
public $cardPrice; //Int;
public $cardOnCash; //Decimal;
public $returnCode; //string;
public $returnDescription; //string;
}

/**
* The soap client proxy class
*/
class Net2E
 {
	public $soapClient;

	private static $classmap = array(
		'TopupPpCardForPartners'=>'TopupPpCardForPartners',
		'TopupPpCardForPartnersResponse'=>'TopupPpCardForPartnersResponse',

);

function __construct($url='http://123.30.200.141:9000/OnGateBillingServices.asmx?wsdl')
//function __construct($url='http://222.255.38.200/OnGateServices/OnGateBillingServices.asmx?wsdl')
{
$this->soapClient = new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => true));
}


function TopupPpCardForPartners($TopupPpCardForPartners)
{
	$useCardResponse = $this->soapClient->TopupPpCardForPartners($TopupPpCardForPartners);
	return $useCardResponse;
}

}


