<?php
/**
 * Soap client SMSGW
 *
 * Autogenerated with the Yii extension wsdl2php.
 */



class smsRequest
{
	public $username; //string;
	public $password; //string;
	public $msisdn; //string;
	public $content; //string;
	public $shortcode; //string;
	public $alias; //string;
	public $params; //string;
}

class smsRequestResponse
{
	public $return; //string;
}

/**
 * The soap client proxy class
 */
class SMSGW
{
	public $soapClient;

	private static $classmap = array(
			'smsRequest'=>'smsRequest',
			'smsRequestResponse'=>'smsRequestResponse',

	);

// 	function __construct($url='http://127.0.0.1:82/wsdl/smsws.wsdl')
	function __construct($url='http://10.58.128.105:8300/smsws?wsdl')
	{
		$this->soapClient = new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => true));
	}


	function smsRequest($smsRequest)
	{
		$smsRequestResponse = $this->soapClient->smsRequest($smsRequest);
		Yii::log("REQUEST:\n" . $this->soapClient->__getLastRequest() . "\n");
		Yii::log("RESPONSE:\n" . $this->soapClient->__getLastResponse() . "\n");
		return $smsRequestResponse;
	}
}


