<?php
/**
* Soap client Voucher
*
* Autogenerated with the Yii extension wsdl2php.
*/



class useCard
{
public $issuer; //string; ma don vi phat hanh MOBI|VINA|VT|VCOIN|GATE|GM
public $cardSerial; //string; seri the 11->15, GM: 10->12
public $cardCode; //string; ma the MOBI: 12,14,15| VINA: 12,14 | VT: 13, 14,15 | GM: 12 chi gom so + ky tu
public $transRef; //string; ma giao dich (< 30 ky tu) 
public $partnerCode; //string; Ma doi tac
public $password; //string;
public $signature; //string;
}

class useCardResponse
{
public $return; //string;
}

class getTransactionDetail
{
public $transRef; //string;
public $partnerCode; //string;
public $password; //string;
public $signature; //string;
}

class getTransactionDetailResponse
{
public $return; //string;
}

/**
* The soap client proxy class
*/
class Voucher 
 {
	public $soapClient;

	private static $classmap = array(
		'useCard'=>'useCard',
		'useCardResponse'=>'useCardResponse',
		'getTransactionDetail'=>'getTransactionDetail',
		'getTransactionDetailResponse'=>'getTransactionDetailResponse',

);

function __construct($url='http://125.212.219.11/voucher/VoucherService?wsdl')
{
$this->soapClient = new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => true));
}


function useCard($useCard)
{
	$useCardResponse = $this->soapClient->useCard($useCard);
	return $useCardResponse;
}

function getTransactionDetail($getTransactionDetail)
{
	$getTransactionDetailResponse = $this->soapClient->getTransactionDetail($getTransactionDetail);
	return $getTransactionDetailResponse;
}
}


